Use mapstruct mapper for auto generation of converters
redhat-appdev-practice/spring-rest-surveygroups pull request #2
Opened 2020-04-23 16:25 UTC by NateLove

2020-04-27 18:52 UTC, willowmck requested changes
Since this change is intended to replace the use of HttpUtils, please also remove that file.

2020-04-27 18:52 UTC, willowmck commented on src/main/java/com/redhat/appdevpractice/samples/survey/http/utils/HttpMapper.java
> +import org.mapstruct.MapMapping;
Remove this unused import.

2020-04-27 19:47 UTC, NateLove commented on src/main/java/com/redhat/appdevpractice/samples/survey/http/utils/HttpMapper.java
> +import org.mapstruct.MapMapping;
removed

2020-04-28 10:59 UTC, willowmck approved these changes

2020-04-28 10:59 UTC, merged